id: IDD5E9AD4
ocr_import_info:
  timestamp: '2023-06-16T15:01:23.723944+00:00'
  batch_id: batch-1527
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Openpecha
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-16 15:03:54.871690+00:00
last_modified: 2023-06-16 15:03:54.871696+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W26677
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26677
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་ཆེན་ཁྲིད་སྐོར་བདུད་འཇོམས་གླིང་པའི་གཏེར་ཆོས།
  languages:
  - bo
  author: བདུད་འཇོམས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9570794533140209
  ocr_word_median_confidence_index: 0.9978882
bases:
  I5667:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5667
      total_pages: 238
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5667.txt
    statistics:
      ocr_word_median_confidence_index: 0.9978882
      ocr_word_mean_confidence_index: 0.9570794533140209
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
